name: Build Example App Preview

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        type: choice
        required: true
        default: all
        options:
          - all
          - android
          - ios

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🏗 Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true

      - name: 🏗 Setup expo
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🔨 EAS build
        working-directory: apps/mobile
        run: eas build --non-interactive --no-wait --platform=${{ github.event.inputs.platform }} --profile=preview
